name: Master CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno v1.33.4
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.4

      - name: Verify formatting
        run: deno fmt mod.ts src/ --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable --coverage=cov_profile

      - name: Generate coverage reports
        run: deno coverage cov_profile --lcov > cov_profile.lcov

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
