name: Master CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno v2.x
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Setup LCOV        
        run: sudo apt install -y lcov

      - name: Verify formatting
        run: deno task fmt

      - name: Run linter
        run: deno lint

      - name: Run tests and coverage
        run: deno task cover

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
